### ISSUE TITLE
Cant find some classes

### ISSUE THREAD

**Issue by yoosefi12** [clarin-eric/oai-harvest-manager#9]
Hi
I can't find some classes in  **nl.mpi.oai.harvester.generated** package like
 nl.mpi.oai.harvester.generated.**OverviewType** or nl.mpi.oai.harvester.generated.**ModeType** or
nl.mpi.oai.harvester.generated.**ScenarioType** 

these classes used in nl.mpi.oai.harvester.cycle package.

Can you help me?

**Comment by kjvandelooij** [comment]
Hi,

the classes in the generated package are, like the name suggest, generated.
So if they are not there, which is likely to the be case in the repository,
the should be generated. In case of the harvest manager, this is done using
JAXB. Refer to documentation on JAXB for instructions on how to generate
these classes. You could also have a look at maven level or at instructions
that come with the IDE.

Hope this helps,

Kees Jan

**Comment by yoosefi12** [comment]
Thanks for your comment. 

Yoosefi Ali
